export const SET_PRODUCT_VALUE = 'SET_PRODUCT_VALUE';
export const SET_PRODUCT_FETCHING = 'SET_PRODUCT_FETCHING';
export const SET_ORIGINAL_OBJECT = 'SET_ORIGINAL_OBJECT';
export const SET_ORIGINAL_CHANGED = 'SET_ORIGINAL_CHANGED';
